### ISSUE TITLE
import error in __init__

### ISSUE THREAD

**Issue by keunwoochoi** [rabitt/motif#22]
Hi Rachel,
Thanks for this great repo. I had this strange error when I tried to import motif on ubuntu 16.04.1. I don't really get it, I could import all other packages which would have the same __init__ setups. Is it only me? Do you have any idea? 

```
$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import motif
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/motif/__init__.py", line 3, in <module>
    from . import contour_extractors
ImportError: cannot import name 'contour_extractors'
>>>
```

**Comment by pauloacmartinez** [comment]
I am also having the same issue
